time_weight: 0.5
time_ref: 0.01
check_with_finite_diff: false
soft_control_bounds: false
CALLBACKS: false
use_finite_diff: false
use_warmstart: true
rollout_warmstart: false
repair_init_guess: false
control_bounds: true
states_reg: false
solver_id: 0
disturbance: 1e-5
num_threads: 1
th_stop: 1e-1
init_reg: 1e5
th_acceptnegstep: .1
noise_level: 1e-5
u_bound_scale: 1
max_iter: 200
debug_file_name: /tmp/debug_file.yaml
weight_goal: 200.0
collision_weight: 150.0
smooth_traj: false
shift_repeat: false
track_reference: false
penalty_iterations: 1