time_weight: 0.0
time_ref: 0.0
check_with_finite_diff: false
soft_control_bounds: false
CALLBACKS: false
use_finite_diff: false
use_warmstart: true
rollout_warmstart: false
repair_init_guess: false
control_bounds: true
states_reg: false
solver_id: 0
disturbance: 1e-5
num_threads: 1
th_stop: 1e-2
init_reg: 1e2
th_acceptnegstep: .3
noise_level: 1e-4
u_bound_scale: 1
max_iter: 100
debug_file_name: /tmp/debug_file.yaml
weight_goal: 200
collision_weight: 100
smooth_traj: false
shift_repeat: false
