time_weight: 0.0
time_ref: 0.0
check_with_finite_diff: false
soft_control_bounds: false
CALLBACKS: true
use_finite_diff: false
use_warmstart: true
rollout_warmstart: false
repair_init_guess: false
control_bounds: true
states_reg: true
solver_id: 0
disturbance: 1e-1
num_threads: 1
th_stop: 0.01
init_reg: 1e-1
th_acceptnegstep: 0.01
noise_level: 0.0
u_bound_scale: 1
max_iter: 200
debug_file_name: /tmp/debug_file.yaml
weight_goal: 100.0
collision_weight: 300.0
smooth_traj: false
shift_repeat: false
reg_control: true
control_reg_weight: 0.2
penalty_iterations: 1