pc-dbcbs:
  default:
    delta_0: 0.5
    delta_rate: 0.9
    num_primitives_0: 1000
    max_motions: 30000
    num_primitives_rate: 0.05
    alpha: 0.6
    filter_duplicates: True
    heuristic1: "no-reverse-search"
    heuristic1_delta: 1.0
    payload:
      solve_p0: True
      anytime: False
      p0_init_guess: [0.0, 0.0, 0.4]
      tol: 0.3
    payload_opt:
      mu: 1.0
      lambda: 0.0
      w_strech: 10.0
      w_bounds: 10.0
      w_coll:   100.0
      d_safe: 0.1
      bounds_min: [-2.0, -0.5, 0.0]
      bounds_max: [2.0, 0.5, 1.0]
      
